ALTER TABLE ip2nation ENGINE=INNODB;
ALTER TABLE ip2nationCountries ENGINE=INNODB;
ALTER TABLE wp_amazon_link_cache ENGINE=INNODB;
ALTER TABLE wp_commentmeta ENGINE=INNODB;
ALTER TABLE wp_comments ENGINE=INNODB;
ALTER TABLE wp_ewwwio_images ENGINE=INNODB;
ALTER TABLE wp_gpi_api_error_logs ENGINE=INNODB;
ALTER TABLE wp_gpi_custom_urls ENGINE=INNODB;
ALTER TABLE wp_gpi_page_blacklist ENGINE=INNODB;
ALTER TABLE wp_gpi_page_reports ENGINE=INNODB;
ALTER TABLE wp_gpi_page_stats ENGINE=INNODB;
ALTER TABLE wp_gpi_summary_snapshots ENGINE=INNODB;
ALTER TABLE wp_huge_it_share_params ENGINE=INNODB;
ALTER TABLE wp_huge_it_share_params_posts ENGINE=INNODB;
ALTER TABLE wp_links ENGINE=INNODB;
ALTER TABLE wp_options ENGINE=INNODB;
ALTER TABLE wp_postmeta ENGINE=INNODB;
ALTER TABLE wp_posts ENGINE=INNODB;
ALTER TABLE wp_statigram_widget ENGINE=INNODB;
ALTER TABLE wp_term_relationships ENGINE=INNODB;
ALTER TABLE wp_term_taxonomy ENGINE=INNODB;
ALTER TABLE wp_termmeta ENGINE=INNODB;
ALTER TABLE wp_terms ENGINE=INNODB;
ALTER TABLE wp_usermeta ENGINE=INNODB;
ALTER TABLE wp_users ENGINE=INNODB;
ALTER TABLE wp_w3tc_cdn_queue ENGINE=INNODB;
ALTER TABLE wp_wdi_feeds ENGINE=INNODB;
ALTER TABLE wp_wdi_themes ENGINE=INNODB;
ALTER TABLE wp_wpaa_cache ENGINE=INNODB;
ALTER TABLE wp_wpaa_template ENGINE=INNODB;

ALTER TABLE wp_term_relationships ADD INDEX idx_term_taxonomy_id_object_id(term_taxonomy_id,object_id);
ALTER TABLE wp_postmeta ADD INDEX idx_post_id_meta_key(post_id,meta_key(255));
ALTER TABLE wp_postmeta ADD INDEX idx_meta_key_meta_value(meta_key(255),meta_value(1));
ALTER TABLE wp_posts ADD INDEX idx_ID_post_type_post_status_post_date(ID,post_type,post_status,post_date);
ALTER TABLE wp_options ADD INDEX idx_autoload(autoload);
ALTER TABLE wp_users ADD INDEX idx_user_login(user_login);
ALTER TABLE wp_comments ADD INDEX idx_comment_approved(comment_approved);
ALTER TABLE wp_comments ADD INDEX idx_comment_approved_comment_date_gmt(comment_approved,comment_date_gmt);
